import { APP_NAME } from "@/constants/default";
import Head from "next/head";
import { LayoutProps } from "types/props";
import Navbar from "./Partials/Navbar";

import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"] });

export default function Layout({ title, children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>{title ?? APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={inter.className}>
        <Navbar />
      </header>
      <main className={inter.className}>{children}</main>
      <footer className={inter.className}></footer>
    </>
  );
}
